### ISSUE TITLE
Most dependencies should be in `Imports` rather than `Depends`

### ISSUE THREAD

**Issue by kelly-sovacool** [NIDAP-Community/DSPWorkflow#127]
The package dependencies in the description file are listed under `Depends`, but most of them except the R version should likely go under `Imports` unless you have a good reason. See details here: https://r-pkgs.org/dependencies-mindset-background.html#sec-dependencies-imports-vs-depends

**Comment by escauley** [comment]
Sounds good! I will switch those over and test the package

**Comment by escauley** [comment]
All dependencies in the DESCRIPTIOn excpet for R have been moved to "imports" instead of "depends". The vignette ran successfully for this update and the changes were pushed to main
